### PR TITLE
REST API v1

### PR DESCRIPTION
**Pull request by cnweaver**
This set of patches implements a new (major) version of the REST API. 

The breaking change is that objects which have unique names (users, groups, SCRAM credentials, and Kafka topics) are looked up by those names, instead of their internal primary (surrogate) keys. Names are also provided in API responses when a foreign key appears for one of these objects. With these changes, clients should require fewer lookups to do common operations, as they will not have to perform the conversion between the object names which are meaningful to them and the internal IDs. 

A set of route for 'reflexive' queries are also added. These also serve to reduce lookups and enable a client to bootstrap its knowledge of the context in which it is operating. The `current_user` routes provide information about the user making the request (or on behalf of whom the request is being made), including the user record itself, the user's SCRAM credentials, and the user's group memberships. The `current_credential` routes provide information about the credential being used to make the request, including the record for the credential itself, the explicit permission objects attached to that credential, and the effective permissions that credential has for a given Kafka topic. These routes are intended to allow largely stateless proxy tools to act on behalf of a user, gaining the context information they need from the user's authentication.

### CODE REVIEW

**Comment by manning-ncsa** [comment]
@cnweaver Did you consider [the versioning pattern described in the DRF docs](https://www.django-rest-framework.org/api-guide/versioning/#namespaceversioning)?

**Comment by cnweaver** [comment]
I had not, as I had not noticed it in the docs. It seems rather complicated, and given that the versioning is already implemented, it doesn't seem like there would be much point in trying to switch?

**Comment by manning-ncsa** [comment]
Another thing that would be nice is to generate and store an OpenAPI document capturing this new API. Recently I [followed this guide to generate an interactive spec](https://www.django-rest-framework.org/topics/documenting-your-api/#generating-documentation-from-openapi-schemas) at a dedicated endpoint.

**Comment by manning-ncsa** [comment]
> I had not, as I had not noticed it in the docs. It seems rather complicated, and given that the versioning is already implemented, it doesn't seem like there would be much point in trying to switch?

No, I'm not saying you should switch now after all that work, but perhaps in subsequent iterations it may be worth a look at their pattern in case it saves tedious programming as DRF does in so many ways.

**Comment by cnweaver** [comment]
> Another thing that would be nice is to generate and store an OpenAPI document capturing this new API. Recently I [followed this guide to generate an interactive spec](https://www.django-rest-framework.org/topics/documenting-your-api/#generating-documentation-from-openapi-schemas) at a dedicated endpoint.

I definitely want to do this to generate documentation, but the automatic output leaves a lot to be desired, from what I saw in my tests of it. It seemed likely that it could be a starting point but would require a lot of post-processing by hand to make useful (mostly because the capturing of the serialization formats was pretty incomplete, IIRC). I'll have to look at this further as we converge on the content of the API. I do intend to address that and have some form of documentation before merging this PR.

**Comment by manning-ncsa** [comment]
That's about all I can contribute to this review. I have not tested any of these changes personally, but I see no red flags.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1

**Pull request merged**
